SRC=Listing_9.10
FLAGS=-std=c++11
TAR=$(SRC)
LIB=m

C:
	gcc $(FLAGS) -g -o $(TAR) $(SRC).c
	./$(TAR)

cpp:
	@#Listing_11.19~Listing_11.20
	g++ -g -o Listing_11.21 Listing_11.20.cpp Listing_11.21.cpp -lm
	./Listing_11.21
#Listing_11.16~Listing_11.18
#g++ -g -o Listing_11.18 Listing_11.17.cpp Listing_11.18.cpp -lm
#./Listing_11.18
#Listing_11.13~Listing_11.15
#g++ -g -o Listing_11.15 Listing_11.14.cpp Listing_11.15.cpp -lm
#./Listing_11.15
#Listing_11.10~Listing_11.12
#g++ -g -o Listing_11.12 Listing_11.11.cpp Listing_11.12.cpp -lm
#./Listing_11.12
#Listing_11.7~Listing_11.9
#g++ -g -o Listing_11.9 Listing_11.8.cpp Listing_11.9.cpp -lm
#./Listing_11.9
#Listing_11.4~Listing_11.6
#g++ -g -o Listing_11.6 Listing_11.5.cpp Listing_11.6.cpp -lm
#./Listing_11.6
#Listing_11.1~Listing_11.3
#g++ -g -o Listing_11.3 Listing_11.2.cpp Listing_11.3.cpp -lm
#./Listing_11.3

perl:
	perl $(SRC).pl

exec:
	./$(SRC)

temp:
	g++ -g -c test_of_extern_c.cpp
